In [1]:
import numpy as np

# 0차원 텐서(스칼라)

In [2]:
d = np.array(5)
print('텐서의 차원 :', d.ndim)
print('텐서의 크기(shape) :', d.shape)

텐서의 차원 : 0
텐서의 크기(shape) : ()


# 1차원 텐서(벡터)
- 주의할 점은 벡터에서도 차원이라는 용어를 쓰는데, 벡터의 차원과 텐서의 차원은 다른 개념이라는 점입니다. 아래의 예제는 4차원 벡터이지만, 1차원 텐서입니다. 1D 텐서라고도 합니다.

In [3]:
d = np.array([1,2,3,4])
print('텐서의 차원 :', d.ndim)
print('텐서의 크기(shape) :', d.shape)

텐서의 차원 : 1
텐서의 크기(shape) : (4,)


# 2차원 텐서(행렬)

In [4]:
# 3행 4열의 행렬
d = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print('텐서의 차원 :', d.ndim)
print('텐서의 크기(shape) :', d.shape)

텐서의 차원 : 2
텐서의 크기(shape) : (3, 4)


# 3차원 텐서(다차원 배열)

In [5]:
d = np.array([
            [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 11, 12, 13, 14]],
            [[15, 16, 17, 18, 19], [19, 20, 21, 22, 23], [23, 24, 25, 26, 27]]
            ])

print('텐서의 차원 :',d.ndim)
print('텐서의 크기(shape) :',d.shape)

텐서의 차원 : 3
텐서의 크기(shape) : (2, 3, 5)


# 벡터와 행렬의 연산

In [6]:
import numpy as np

## 벡터와 행렬의 덧셈과 뺄셈

In [7]:
A = np.array([8, 4, 5])
B = np.array([1, 2, 3])
print('두 벡터의 합 :',A+B)
print('두 벡터의 차 :',A-B)

두 벡터의 합 : [9 6 8]
두 벡터의 차 : [7 2 2]


In [8]:
A = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
B = np.array([[5, 6, 7, 8],[1, 2, 3, 4]])
print('두 행렬의 합 :')
print(A + B)
print('두 행렬의 차 :')
print(A - B)

두 행렬의 합 :
[[15 26 37 48]
 [51 62 73 84]]
두 행렬의 차 :
[[ 5 14 23 32]
 [49 58 67 76]]


## 벡터의 내적과 행렬의 곱셈
- 내적이 성립하기 위해서는 두 벡터의 차원이 같아야 하며, 두 벡터 중 앞의 벡터가 행벡터(가로 방향 벡터)이고 뒤의 벡터가 열벡터(세로 방향 벡터)여야 합니다.

In [9]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print('두 벡터의 내적 :',np.dot(A, B))

두 벡터의 내적 : 32


In [10]:
A = np.array([[1, 3],[2, 4]])
B = np.array([[5, 7],[6, 8]])
print('두 행렬의 행렬곱 :')
print(np.matmul(A, B))

두 행렬의 행렬곱 :
[[23 31]
 [34 46]]
